### ISSUE TITLE
calendar overview shows previous date not the selected date

### ISSUE THREAD

**Issue by FloVanGH** [elementary/calendar#109]
![screenshot from 2017-05-02 18 30 26](https://cloud.githubusercontent.com/assets/6715107/25628139/70e8b866-2f65-11e7-8a12-fcc90ccba06d.png)

- MacBook Pro 13 (2012 not Retina)
- elementary OS Loki 64bit
- All current updates are installed

**Comment by jorchube** [comment]
When selecting a day in the grid, the sorting method of the AgendaView gets the selected date in local timezone, in this form:

YYY-MM-DDT00:00:00[+|-]hhmm

Then the AgendaView proceeds to get the events of this date, using a sorting function that does:

(1) Gets the selected date and converts to UTC
(2) Strips the new date from everything except year, month and day
(3) Generates a time range from what it gets in (2) to the same date plus one day
(4) Gets all events whithin the range generated in (3)


The problem lies in (2), when in timezones at the East respect UTC.

Lets check what happens with two examples with the steps 1-3 described above:

First example: the selected date is 2017-05-17T00:00:00-0600, which is at the West respect UTC timezone

(1) 2017-05-17T00:00:00-0600 to UTC : 2017-05-17T05:00:00+0000
(2) 2017-05-17T05:00:00+0000 strip: 2017-05-17T00:00:00+0000
(3) 2017-05-17T00:00:00+0000 generates range: FROM:2017-05-17T00:00:00+0000 TO:2017-05-18T00:00:00+0000

This is OK.


Second example: the selected date is 2017-05-17T00:00:00+0200, which is at the East respect UTC timezone

(1) 2017-05-17T00:00:00+0200 to UTC : 2017-05-16T02:00:00+0000
(2) 2017-05-16T02:00:00+0000 strip: 2017-05-16T00:00:00+0000
(3) 2017-05-16T00:00:00+0000 generates range: FROM:2017-05-16T00:00:00+0000 TO:2017-05-17T00:00:00+0000

This is not OK. AgendaView will show event of the day prior to the selected one.

I have done a pull request that might fix this. Let's see.
