### ISSUE TITLE
Improve look of all-day events in calendar view

### ISSUE THREAD

**Issue by phase1geo** [elementary/calendar#261]
There is no visual distinction betwen all-day events and timed events. It would also be nice if an all-day event covered multiple days to make it more evident that you have a single event that covers multiple days.

**Comment by cassidyjames** [comment]
It looks like other apps/services like Google Calendar and GNOME Calendar distinguish them in a few ways:

- Multi-day events visually span multiple days instead of showing an individual item on each day. This also means they only how the even details on the first visible day, cleaning up some of the clutter.
- Timed (not all-day) events show less visually prominent, often with a color-coded dot or icon next to the text instead of a whole colored block around the text.
- The time of non-all-day events is often shown next to the event title if there's room, making the calendar more useful at a glance.

On mobile, Google Calendar is much more similar to our current implementation, likely due to being space constrained. So there's an argument for something a little more responsive/adaptive based on available space as well.

**Comment by cassidyjames** [comment]
Due to the similarity to #44 I think I'm gonna actually close this as a dupe. Sorry for the noise!
