### ISSUE TITLE
Import ICS dialog popover is cut off

### ISSUE THREAD

**Issue by danrabbit** [elementary/calendar#299]
![screenshot from 2018-12-06 14 24 22 2x](https://user-images.githubusercontent.com/7277719/49615841-957ee500-f963-11e8-970c-34ab752a2b3d.png)

We probably should just put the listbox directly in the dialog and not use a popover here

**Comment by peteruithoven** [comment]
Data from #383 

When I import a .ics file I can't seem to select the calendars that fall above the import window:
![screen record from 2019-03-03 22 50 25](https://user-images.githubusercontent.com/523210/53702438-37995680-3e07-11e9-8969-d586c328077a.gif)

I notice that I interact with the calendar app below, when I double click on an calendar tha'ts above a day from the previous month the calendar will navigate to that month.

**Comment by mcclurgm** [comment]
This appears to be a GTK issue: all popovers (and other related menu types?) that are larger than their windows get cut off in the non-Wayland implementation. It's a design flaw in all of GTK 3 ([GTK bug](https://gitlab.gnome.org/GNOME/gtk/issues/543)). So it also happens to the same popover in the generic edit dialog, and potentially anywhere else we include popovers.

Since there's nothing we can do about this until either we port to GTK 4 or Elementary moves to Wayland, I'm not sure what to do. It's not a good experience, so it would be nice to have a workaround. I don't know what that would be, beyond somehow ensuring that the dialogs are large enough, or moving the grid into the dialog itself somehow (as opposed to a popover).

**Comment by marbetschar** [comment]
Ran into the same thing:

![Screenshot from 2020-12-21 15-12-39](https://user-images.githubusercontent.com/392542/102786166-5fbcc580-439f-11eb-8088-37a8f3b38224.png)

**Comment by mcclurgm** [comment]
So what do we think this should look like? Seems obvious to me that we should embed the picker in the main window somehow. (Which may be better anyway, since it flattens the interaction and requires fewer clicks?)

We could just take the current picker and instead of placing it in a popover, we could place it in the main grid. It doesn't look very good like that though, since it highlights the selected item with a cell background highlight. This isn't a pattern I've seen anywhere else. Is there anything we can do to make it look better? One thought I've had is we could put a check mark at the trailing edge of the selected row and keep a standard transparent background. I've seen that pattern around in Builder and such, but I don't know if elementary uses it.

@elementary/ux thoughts about this?

**Comment by danrabbit** [comment]
@mcclurgm yeah I think we should put the list inside the dialog in a Gtk.Frame and like you said use a check to show the selected item. I think another place we use this pattern is in the Feedback app
