### ISSUE TITLE
can't add caldav

### ISSUE THREAD

**Issue by Surfels** [elementary/calendar#381]
I have done a new install of eos and as always I wanted to add my caldav (mailbox.org). But whenever I add a new calender the app doesn't save the changes.

**Comment by peteruithoven** [comment]
Could you share how you attempted to add it? 
it works for me with NextCloud. I need to copy a url per calender, for example my personal calendar would
```
https://{website}.nl/remote.php/dav/calendars/peteruithoven/personal/
```
This can than be added as Caldav. 

Also note, as far as I understand it, in the future connections to providers like NextCloud or Mailbox will be managed from the online account settings instead of in the Calendar app.

**Comment by Surfels** [comment]
Ok. I have it done like you said... after a restart of my machine I tested it again.. and now it works.
Maybe a temporary problem mailbox.org. Thanks so far.
