### ISSUE TITLE
caledar and mail error connecting to google account

### ISSUE THREAD

**Issue by paulo8448** [elementary/calendar#438]
in case google is blocking authentication, in calendar it shows an error and asks for the password again, in the mail is asking for the password stating that it is wrong but the password is correct.

erro no calendar   
![Captura de tela de 2019-10-03 12-42-29](https://user-images.githubusercontent.com/33562708/66143346-62d26700-e5dd-11e9-9bd9-63fc297347ac.png)

erro no mail 
![Captura de tela de 2019-09-26 11-52-05](https://user-images.githubusercontent.com/33562708/66143450-90b7ab80-e5dd-11e9-8c00-1133bb6ee364.png)

**Comment by ryonakano** [comment]
![screenshot from 2018-06-11 20-55-46](https://user-images.githubusercontent.com/26003928/41230203-db11681c-6db9-11e8-8817-1b00e4db65c8.png)

Do you enable the "Allow less secure apps" option in Google's "My Account" page? I guess this is probably because neither Mail and Calendar support OAuth 2.0 (see #244 and https://github.com/elementary/mail/issues/41).

**Comment by paulo8448** [comment]
The problem involving mail has resolved. Now the calendar does not enter now he does not even want to ask my password to synchronize with the calendar.

**Comment by ryonakano** [comment]
> Now the calendar does not enter now he does not even want to ask my password to synchronize with the calendar.

I guess this is expected behavior?

**Comment by paulo8448** [comment]
Thanks for your support, really the problem has solved. But, we have another problem. i going close this problem and alert another. Waitin another help. Thanks!
