### ISSUE TITLE
Editing the title of an event reschedules it to today's next whole hour

### ISSUE THREAD

**Issue by cassidyjames** [elementary/calendar#453]
Looks to be a regression from #209. Might require pressing Enter in the event name when editing, I haven't fully tracked down when it happens but it's fairly reproducible.

**Comment by Thalexander** [comment]
ParserEn (line 185) and ParserDe (line 150) both work by assuming the time as being today's next whole hour and the modify that based on the text, the parsing runs on enter in the event title and so causes this issue. This does not occur repeatedly in the same panel though as parsing only happens once, so changing the event name again without saving and then pressing enter will just save the event rather than re-parsing. Unrelated to #209, although it uses the previous logic for the next whole hour, we may want to change that to match the new behaviour.
