### ISSUE TITLE
New event appears twice in side bar

### ISSUE THREAD

**Issue by wolframroesler** [elementary/calendar#478]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
After creating a new event in the calendar, it appears twice in the "During the day" section of the side bar (right hand side of the screen).

After closing and re-opening the Calendar app, the new event appears only once.

When deleting the event while it's shown twice in the side bar, one of the two side bar items disappears but the other remains.

### To Reproduce
1. Click "Create a new event" (or press ^N)
1. Enter title, date, etc.
1. Save the new event
1. Look at the "During the day" section in the side bar to the right of the screen

### Expected behavior
The new event is expected to appear only once in the side bar.

### Screenshots or screen recordings

![doubleitem](https://user-images.githubusercontent.com/25565229/71480975-4c166780-27fc-11ea-9e3e-a2410614bc7b.png)

### Logs

```
$ G_MESSAGES_DEBUG=all io.elementary.calendar
...
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.166: individual-aggregator.vala:483: Setting primary store IDs to defaults.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.166: individual-aggregator.vala:503: Primary store IDs are 'eds' and 'system-address-book'.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.166: individual-aggregator.vala:513: Constructing IndividualAggregator 0x1ba9f70
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.166: Using built-in backends key file '/home/wolfram/.local/share/folks/backends.ini' (override with environment variable FOLKS_BACKEND_STORE_KEY_FILE_PATH)

** (io.elementary.calendar:8418): CRITICAL **: 16:11:19.180: CalendarModel.vala:123: No calendar client was found

** (io.elementary.calendar:8418): CRITICAL **: 16:11:19.181: CalendarModel.vala:123: No calendar client was found
Gtk-Message: 16:11:19.272: GtkDialog mapped without a transient parent. This is discouraged.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.275: Using built-in backend dir '/usr/lib/x86_64-linux-gnu/folks/43/backends' (override with environment variable FOLKS_BACKEND_PATH)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.275: backend-store.vala:631: Searching for modules in folder '/usr/lib/x86_64-linux-gnu/folks/43/backends' ..
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.276: backend-store.vala:631: Searching for modules in folder '/usr/lib/x86_64-linux-gnu/folks/43/backends/key-file' ..
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.278: backend-store.vala:746: Finished searching for modules in folder '/usr/lib/x86_64-linux-gnu/folks/43/backends/key-file'
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.278: backend-store.vala:631: Searching for modules in folder '/usr/lib/x86_64-linux-gnu/folks/43/backends/eds' ..
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.279: backend-store.vala:746: Finished searching for modules in folder '/usr/lib/x86_64-linux-gnu/folks/43/backends/eds'
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.279: backend-store.vala:746: Finished searching for modules in folder '/usr/lib/x86_64-linux-gnu/folks/43/backends'
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.279: backend.vala:40: Constructing Backend ‘key-file’ (0x2df4a00)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.280: backend-store.vala:799: Loaded module source: '/usr/lib/x86_64-linux-gnu/folks/43/backends/key-file/key-file.so'
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: backend.vala:40: Constructing Backend ‘eds’ (0x2b7edb0)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: backend-store.vala:799: Loaded module source: '/usr/lib/x86_64-linux-gnu/folks/43/backends/eds/eds.so'
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: No catch-all entry in the backend key file. Enabling unlisted backends.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: Found no entry for backend 'eds'.enabled in backend keyfile. Enabling according to 'all-others' setting.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: No catch-all entry in the backend key file. Enabling unlisted backends.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: Found no entry for backend 'key-file'.enabled in backend keyfile. Enabling according to 'all-others' setting.
(io.elementary.calendar:8418): key-file-DEBUG: 16:11:19.313: Using built-in key file '/home/wolfram/.local/share/folks/relationships.ini' (override with environment variable FOLKS_BACKEND_KEY_FILE_PATH)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.313: persona-store.vala:337: Constructing PersonaStore ‘relationships.ini’ (0x2e0b1f0)
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.314: eds-backend.vala:291: Address book source list changed.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.315: eds-backend.vala:338: Adding address book 'system-address-book'.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: persona-store.vala:337: Constructing PersonaStore ‘system-address-book’ (0x2dfe300)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: backend-store.vala:417: New backend 'eds' prepared
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:987: _backend_persona_store_added_cb(): backend: eds, store: system-address-book (0x2dfe300)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:1932: _maybe_configure_as_primary()
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:945: _set_primary_store()
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:962: Setting primary store to 0x2dfe300 (type ID: eds, ID: system-address-book)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: backend-store.vala:417: New backend 'key-file' prepared
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:987: _backend_persona_store_added_cb(): backend: key-file, store: relationships.ini (0x2e0b1f0)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:1932: _maybe_configure_as_primary()
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.315: individual-aggregator.vala:945: _set_primary_store()
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.450: Successfully finished opening address book 0x2d5a630 for persona store ‘system-address-book’ (0x2dfe300).
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.450: PersonaStore.is-user-set-default changed for store 0x2dfe300 (type ID: eds, ID: system-address-book)
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.450: individual-aggregator.vala:1932: _maybe_configure_as_primary()
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.450: individual-aggregator.vala:1939: Setting primary store IDs to 'eds' and 'system-address-book'.
(io.elementary.calendar:8418): folks-DEBUG: 16:11:19.450: individual-aggregator.vala:945: _set_primary_store()
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.462: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'file_as'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.462: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'mailer'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.462: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'caluri'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.462: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'icscalendar'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'spouse'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'logo'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'wants_html'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'list'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'list_show_addresses'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'anniversary'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'x509Cert'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'pgpCert'.
(io.elementary.calendar:8418): eds-DEBUG: 16:11:19.463: edsf-persona-store.vala:1185: Unsupported/Unknown EDS field name 'im_twitter'.
** (io.elementary.calendar:8418): DEBUG: 16:11:22.197: CalendarModel.vala:131: Adding event 'e0d62c1452cbdb62742c9336958f74c89ae7349c'
** (io.elementary.calendar:8418): DEBUG: 16:11:24.693: Received 2 added event(s) for source 'Wolfram'
** (io.elementary.calendar:8418): DEBUG: 16:11:24.693: CalendarModel.vala:383: Event ['test', Wolfram, e0d62c1452cbdb62742c9336958f74c89ae7349c)]
** (io.elementary.calendar:8418): DEBUG: 16:11:24.693: CalendarModel.vala:383: Event ['test', Wolfram, e0d62c1452cbdb62742c9336958f74c89ae7349c)]
```

## Platform Information

![about](https://user-images.githubusercontent.com/25565229/71480962-40c33c00-27fc-11ea-85f5-663075b89aa6.png)

My calendar is hosted on Nextcloud 17.

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by amz-x** [comment]
I am also experiencing this issue.

**Comment by mcclurgm** [comment]
This appears to be an issue with Google (or maybe general online?) calendars? It happens for me when I add to a google calendar (which I added from GNOME online accounts) but not on a local calendar. I don't have any other online calendars to check this with though.

**Comment by mcclurgm** [comment]
I'm seeing that `on_objects_added` (`core/model/CalendarModel.vala:402`) receives the duplicate events. I think this means that the model we're using gets multiple events out of the Evolution data backend, since it's connected to the same signal as AgendaView's `on_events_added`. This means that the Evolution backend is giving us the duplicate events somehow, and only for online calendars.

It's happening somewhere between calling `client.create_object` in `add_event_async` (`core/model/CalendarModel.vala:129) and the Evolution `objects_added` signal being emitted. I know that `create_object` only produces a single event, but somewhere that's getting lost. It may be an issue with EDS, or how we're using it? I have no idea how to debug this, unfortunately. But this is what I've narrowed it down to.

Now why does the month view not show the duplicates? I have no idea. It seems like it should be getting these duplicate events from the model as well.

**Comment by wolframroesler** [comment]
Thanks for the analysis @mcclurgm. Do you think it's possible to work around the duplicate event? Like, not try to prevent it from being sent, but ignore it on UI level when it occurs?

**Comment by mcclurgm** [comment]
That's a good question. Of course that wouldn't be ideal, because it could mess something else up. But that's speculation..

I think this might be possible. My debug log agrees with what you have, and I'd point out the last piece:
> ```
> ** (io.elementary.calendar:8418): DEBUG: 16:11:22.197: CalendarModel.vala:131: Adding event 'e0d62c1452cbdb62742c9336958f74c89ae7349c'
> ** (io.elementary.calendar:8418): DEBUG: 16:11:24.693: Received 2 added event(s) for source 'Wolfram'
> ** (io.elementary.calendar:8418): DEBUG: 16:11:24.693: CalendarModel.vala:383: Event ['test', Wolfram, e0d62c1452cbdb62742c9336958f74c89ae7349c)]
> ** (io.elementary.calendar:8418): DEBUG: 16:11:24.693: CalendarModel.vala:383: Event ['test', Wolfram, e0d62c1452cbdb62742c9336958f74c89ae7349c)]
> ```

You add one event in `add_event_async`, with UID `e0d62c1452cbdb62742c9336958f74c89ae7349c`. Then we get a response that repeats that same UID twice in `on_events_added`. So maybe we could check whether the same ID is used multiple times? That assumes that every event has a unique UID, which seems reasonable, but I don't see any documentation on the matter.

Two more observations, which are unrelated but may help us track this down. First, occasionally I see the duplicate events in the main calendar view, and actually not in the sidebar. Instead, I see a big blank space in the sidebar where I imagine one could be. This is the exact opposite of #497. This might point to a fragile handling of the duplicate events somehow, if we both see different behavior (I'm compiling from master, if that makes a difference). Second, my system uses `libecal` version 1.2, not 2.0. I think GNOME calendar, which doesn't show this, uses version 2. Maybe the APIs behave more differently than they appear, but that's fully speculation.

**Comment by mcclurgm** [comment]
Alright... with some further digging I think I've figured this out. It seems like there's nothing about what we're doing to _create_ the event that's causing issues. Somehow, Evolution returns 2 events for the Gmail source whenever you add it. I found the exact same behavior when called from GNOME Calendar. So it seems like it's on the client to figure it out.

GNOME doesn't show this behavior, and it looks like that's because of a cache system they have. Whenever they receive an added event, they check whether its UID is already in their database. If it is, they skip the whole process for that component. (This is from cal_data_model_process_added_component() in version 3.28, looks like the function has changed since)

We should be able to implement something like that, but it would require some bookkeeping we don't do right now. I'll see what I can do about it.

**Comment by mcclurgm** [comment]
Good news, it looks like this will be fixed in #560. Putting this here to remember to close when that's merged.

**Comment by funder7** [comment]
Hello, has #560 fixed the problem, and if yes, it's the fix already available in the current version?  
I'm still seeing the appointments twice. 

Thanks

**Comment by mcclurgm** [comment]
That PR is closed and it looks like we're not merging it. So this was fixed there, but won't make it to release. We'll have to re-implement the fix in our code now.

**Comment by funder7** [comment]
So #595 which has been merged doesn't include the fix?

**Comment by wolframroesler** [comment]
Sorry, due to this and many other big and small issues I'm not using elementaryOS any more, so I can't tell if the error still occurs in the current version.

**Comment by funder7** [comment]
> Sorry, due to this and many other big and small issues I'm not using elementaryOS any more, so I can't tell if the error still occurs in the current version.

 I understand. Which OS are you using now?

**Comment by wolframroesler** [comment]
I'm on PopOS now. Almost as pretty as elementary (albeit in a different, less Mac-y way), and much closer to plain Ubuntu (which I'm using at work), yet flatpak-focused and snap-free.
