### ISSUE TITLE
Move Add New Event to a Floating Action Button

### ISSUE THREAD

**Issue by lainsce** [elementary/calendar#484]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
No, it's not, it's a design-only feature request.

**Describe the solution you'd like**
The `Add New Event` button could be relocated as a Floating Action Button, but tailored to our design guidelines; scaled to the display type and carefully made to fit in the app and the system style. This would also mean moving the `Go to Today` button as the first header bar icon.

**Existing work**
As seen on Android™

**Describe alternatives you've considered**
There's no alternatives since this is a design request.

**Additional context**
![cal_fab_mockup](https://user-images.githubusercontent.com/4886639/72588714-ee93a900-38d7-11ea-9948-571e0c76f82f.png)

**Comment by tintou** [comment]
I don't like the fact that it is covering useful content, here it's a day for next month but it can very likely be a day for current month

**Comment by lainsce** [comment]
It could also be in the events sidebar. I just have put it there originally because it seemed to be a UI that affects the calendar. (My mistake of layout)

![cal_fab_mockup](https://user-images.githubusercontent.com/4886639/72626878-3fcc8880-392a-11ea-9754-bf4c0b52fdbc.png)

The above really does make more sense: adding events would ultimately be shown in the events sidebar (primary UI), and a snippet of it on the calendar (secondary UI).

**Comment by danrabbit** [comment]
We had a lengthy discussion in slack and the result basically boils down to:

* FABs make more sense on a mobile interface where they're meant to be used with thumbs but not as much sense on a desktop interface
* FABs are becoming less popular even on Android because they have drawbacks like covering list items
* We currently have lots of lists that have multiple buttons in their inline toolbars, so we need the visual design of action buttons to make sense with more than one action.

There's probably an argument to be made for putting the new event button in the events list, but I think it sounds like there's a pretty strong consensus on the design team that FABs probably don't make sense as a design pattern to adopt for a desktop OS
