### ISSUE TITLE
Width of events side bar is too large with Google calendars

### ISSUE THREAD

**Issue by yerbestpal** [elementary/calendar#561]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The side bar on the right where the overviews of events are shown is far too wide. I have actually managed to slim it down just dragging with the mouse, however ninety percent of the time, it won't allow you.

### To Reproduce
1. Launch Calendar.
2. Try to resize the side bar.

### Expected behavior
It should be possible to change the width of the sidebar to slimmer points. The default width should be slimmer.
### Screenshots or screen recordings

![Screenshot from 2020-06-27 23-45-59](https://user-images.githubusercontent.com/15250241/85933647-662b2280-b8d1-11ea-8942-21129212c842.png)
Note: there are no details visible that I have any problem with being exposed.

## Platform Information
![Screenshot from 2020-06-27 23-54-20](https://user-images.githubusercontent.com/15250241/85933659-8bb82c00-b8d1-11ea-8159-4ec579c59f01.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by yerbestpal** [comment]
Having removed various Google calendar, the sidebar is now adjustable to any size. I will updates after trying a few things out

**Comment by jeremypw** [comment]
For me, the Calendar sidebar width is adjustable to a minimum of about 320px and this setting is restored on re-opening the app so the default size is easily changed by a user.  However, the sidebar width is *not* independent of the window width (unlike Files, Code, Music) which I think it should be.

**Comment by 4jNsY6fCVqZv** [comment]
> For me, the Calendar sidebar width is adjustable to a minimum of about 320px and this setting is restored on re-opening the app so the default size is easily changed by a user.

For me this feature somehow creates a disadvantage. As soon as I have changed the size of the sidebar once, consciously or unconsciously, I cannot reset it to the default. I feel the same with other elementary apps in this matter.

>  However, the sidebar width is not independent of the window width (unlike Files, Code, Music) which I think it should be.

To what extent would this be an improvement for Calendar?

**Comment by jeremypw** [comment]
>To what extent would this be an improvement for Calendar?

Its just the way sidebars work in most apps. Resizing two widgets in an unobvious way with one action just feels wrong.

**Comment by yerbestpal** [comment]
Very strange, but I only seemed to experience this issue when I have Google calendars added. Since removing them all, I have been unable to reproduce. I wonder if the events generated in Google calendars contained contents that were somehow influencing the event in the sidebar as well as the surrounding widgets?

**Comment by jeremypw** [comment]
I have changed the issue description to reflect your findings.

**Comment by mcclurgm** [comment]
I think the issue here is that some widgets are overly long, whether they're visible or not. I just went through the process of figuring out a case where that happened to me and found that the culprit was an URL in the location field of one of my events. This was super long, so it forced a minimum width because of something in Gtk layout that I don't understand. But when I changed the contents of the long label (using the Gtk inspector) the sidebar instantly became resizable to smaller values. (Note that this label appears twice, since it's in both the "Today" and "upcoming" lists in the agenda view.)

You should be able to recreate this by editing the location label of any event to anything with a long string of letters (the URL for this issue doesn't count, since it breaks on punctuation :slightly_smiling_face:). When the width of the non-breakable string becomes wider than the current sidebar, it starts growing.

So I think the solution is to change the wrap mode to WORD_CHARS instead of WORD. This could lead to some weird-ish problems where it _could_ wrap in the middle of a real word, but those should be rare and I think it's better than an inexplicably wide sidebar that only appears sometimes. I'll make a PR for this when I have time.
