### ISSUE TITLE
All day events incorrectly shown in agenda

### ISSUE THREAD

**Issue by jeremypw** [elementary/calendar#642]
## What Happened
An all day event occuring two days after the current day appears in the Agenda under the heading "Tomorrow".  An all day event actually starting on the following day does not appear. The screenshot below was taken on Saturday - it shows events all day Monday under "Tomorrow".

![Screenshot from 2020-11-29 06 14 17](https://user-images.githubusercontent.com/10513844/100547879-0f9b8900-3261-11eb-8692-ae9c41aad9e4.png)

## Expected Behavior
The Agenda should show an all day event starting on the following day under the heading "Tomorrow" (and not events starting on other days).

## Steps to Reproduce
1. Create an all day event with the start date set to the following day.
2. Show the calendar - see example screenshot.

## Platform Information
Elementary 6.0 Next in Virtualbox.

**Comment by mcclurgm** [comment]
Are you sure this was taken on a Saturday? The current day highlight is on Sunday, in which case the Monday events showing as tomorrow would be correct. You have Saturday selected, but that doesn't impact what's shown in the upcoming views like "tomorrow."

**Comment by mcclurgm** [comment]
The more I think about this, what I see here is 100% expected behavior. You say that the all-day event for the following day should appear in the "tomorrow" section, and it does in your screenshot. I think the confusion here may be that you have the 28th selected and expect the 29th to be the "next day," but the way we designed this the "next day" is based on the actual current date not the selected day in the grid. So "today" is the 29th and the "next day" is the 30th. I think there's a design issue I want to file about that, but afaik this isn't actually a bug.

@jeremypw Could you confirm whether what I'm saying makes sense with what you see? Maybe you can try adding an event in the middle of the day following the instructions you gave and see if it shows the same thing I describe. If it's something different then I'll take another look here.

**Comment by jeremypw** [comment]
I cannot reproduce this now so it looks like I got confused about which day it was.  Sorry.

**Comment by mcclurgm** [comment]
Alright, no worries! I'm definitely going to submit a design issue for this, I've seen a few people (including myself) get confused about the days in the sidebar so it could probably use some work to be clearer.
