### ISSUE TITLE
Calendar notifications have not icon

### ISSUE THREAD

**Issue by andirsun** [elementary/calendar#677]
## What Happened

When the notification of event is trigged then the icon shows but when is in the notification panel the icon is missing. 

![Screenshot from 2021-06-30 08-34-43](https://user-images.githubusercontent.com/22928302/123970047-68a9d780-d97e-11eb-990f-40fafe5028dd.png)

## Expected Behavior

Show an icon

## Steps to Reproduce

1.Create event
2. set an alert
3. wait the notification

**Comment by Marukesu** [comment]
> I think the long fix is that we should be using the backgrounding portal stuff instead here

the background portal is not a solution for the non-sandboxed version, because it's generate a .desktop file using the received app-id and that is empty for non-sandboxed apps. we still need to create the autostart file manually in that case.

also, instead of creating a second .desktop file, is it possible to implement the daemon on the main binary like appcenter do?

**Comment by marbetschar** [comment]
FYI: Addressed all the concerns in #702

**Comment by marbetschar** [comment]
Closing since the corresponding PR has been merged.
