### ISSUE TITLE
Events not readable in Calendar app

### ISSUE THREAD

**Issue by Adocentyn** [elementary/calendar#736]
In 6.1, whether in light or dark mode the calendar app displays an unreadable grid and a right bar column that looks empty unless clicked on, in which cases listed events are highlighted in blue. Is there a way to change the colours or enhance the readability? I've searched the web and it appears a similar issue existed all the way back to 2018. A workaround was to recompile the app's source code but I think there might be a better way to do it.

**Comment by danrabbit** [comment]
Can you post a screenshot of the issue? I'm not able to reproduce this. Are you perhaps using a custom stylesheet or have modified the system in a similar way?

**Comment by Adocentyn** [comment]
Here are two screenshots with the light theme. It's worth noting that the appearance is the same with the dark theme enabled.
![Capture d'écran du 2021-12-28 00 25 11](https://user-images.githubusercontent.com/7226366/147513513-cb9bde28-f640-428b-a9d6-33c1afc91be6.png)
![Capture d'écran du 2021-12-28 00 26 01](https://user-images.githubusercontent.com/7226366/147513515-df8f7321-47e2-45bb-afc0-5f764ab178ca.png)

**Comment by danrabbit** [comment]
Ah yeah so it looks like this is the Adwaita stylesheet and the system has clearly been modified with the window controls.

You'll need to use the elementary system stylesheet to avoid this kind of breakage. Adwaita is not API compatible with the elementary stylesheet.

**Comment by danrabbit** [comment]
Ah yeah so it looks like this is the Adwaita stylesheet and the system has clearly been modified with the window controls.

You'll need to use the elementary system stylesheet to avoid this kind of breakage. Adwaita is not API compatible with the elementary stylesheet.

**Comment by nekohayo** [comment]
Out of curiosity, and yes I understand you intend this app to be run "on elementaryOS" etc., but for those who are on other OSes (ex: Fedora) but are still interested in trying out this app or using it on the side, how would users tell the app/system to "use the elementary system stylesheet" for it?

As it is not available on flathub, my only option was to install it via `dnf install elementary-calendar` (which installed version 6.1.1), and I tried to `dnf install elementary*style* elementary*theme*` but there was nothing relevant (i.e. gtk-related) in the proposed packages to install. One thing I am wondering is, since this app is using libadwaita, isn't it able to bundle/enforce the theme it uses anyway, so that my system does not try to apply the Adwaita theme to it?
